FROM maven:3-eclipse-temurin-17 AS build
WORKDIR /app
ADD . .
RUN mvn -DskipTests clean package 

FROM eclipse-temurin:17-jre-jammy
ARG BUILD_ENV=default
ENV SPRING_PROFILES_ACTIVE=${BUILD_ENV}
COPY --from=build /app/target/*.jar /app/runner.jar
EXPOSE 8080
CMD ["java", "-jar", "/app/runner.jar"]